name: materialyoud3
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dynamic_color: ^1.8.1
  shared_preferences: ^2.0.15
  flutter_colorpicker: ^1.1.0

  # ADDED dependencies for Dashboard (search, time formatting, svg)
  intl: ^0.18.0
  url_launcher: ^6.1.10
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # register assets folder (semua file dalam assets/icons/)
  assets:
    - assets/icons/